<?php

namespace AccueilBundle\Repository;

/**
 * AdministrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrationRepository extends \Doctrine\ORM\EntityRepository
{
}
