accueil:
    resource: "@AccueilBundle/Resources/config/routing.yml"
    prefix:   /

accueil_analyse:
    resource: "@AccueilBundle/Controller/AnalyseController.php"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

tests:
    resource: "@TestsBundle/Resources/config/routing.yml"
    prefix:   /tests

