tests_homepage:
    path:     /index
    defaults: { _controller: TestsBundle:Default:index }

tests_animated_transition:
    path:     /transition
    defaults: { _controller: TestsBundle:Default:transition }

tests_structure_bootstrap:
    path:     /structure
    defaults: { _controller: TestsBundle:Default:structure }

tests_cookies:
    path:     /cookies
    defaults: { _controller: TestsBundle:Default:cookies }

tests_header:
    path:     /header
    defaults: { _controller: TestsBundle:Default:header }

tests_menu:
    path:     /menu
    defaults: { _controller: TestsBundle:Default:menu }

tests_tab:
    path:     /tab
    defaults: { _controller: TestsBundle:Default:tab }

tests_calendar:
    path:     /calendar
    defaults: { _controller: TestsBundle:Default:calendar }

tests_sql:
    path:     /sql
    defaults: { _controller: TestsBundle:Default:sql }

tests_js:
    path:     /js
    defaults: { _controller: TestsBundle:Default:js }

tests_user:
    path:     /user
    defaults: { _controller: TestsBundle:Default:user }
