accueil_homepage:
    path:     /
    defaults: { _controller: AccueilBundle:Default:accueil }

accueil_projets:
    path:     /projets/{id}
    defaults: { _controller: AccueilBundle:Default:projets }
    requirements:
        id: \d+

accueil_administration:
    path:     /administration/{id}
    defaults: { _controller: AccueilBundle:Default:administration }
    requirements:
        id: \d+

message:
    path:     /message/{id}
    defaults:
        _controller: AccueilBundle:Default:message
        id: 1
    requirements:
        id: \d+

visites:
    path:     /administration/visites
    defaults: { _controller: AccueilBundle:Default:visites }

analyse:
    path:     /administration/analyse
    defaults: { _controller: AccueilBundle:Analyse:index }