services:
    accueil.beta.html:
        class: AccueilBundle\Beta\BetaHTML
    accueil.beta.listener:
        class: AccueilBundle\Beta\BetaListener
        arguments: ["@accueil.beta.html", "2016-05-15"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    accueil.ip.listener:
        class: AccueilBundle\IP\IPListener
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: processIP }
