services:
    accueil.beta.html:
        class: AccueilBundle\Beta\BetaHTML
    accueil.beta.listener:
        class: AccueilBundle\Beta\BetaListener
        arguments: ["@accueil.beta.html", "01-09-2016"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    accueil.ip.listener:
        class: AccueilBundle\IP\IPListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: processIP }