services:
    accueil.beta.html:
        class: AccueilBundle\Beta\BetaHTML
        #arguments: [@service_id, "plain_value", %parameter%]
    accueil.beta.listener:
        class: AccueilBundle\Beta\BetaListener
        arguments: ["@accueil.beta.html", "2016-10-20"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }        
