<?php

namespace CalendarBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
  public function findEventsByUser( $user ){

    $qb = $this->createQueryBuilder('t');

    $qb
      ->where('t.user = :user')
      ->setParameter('user',$user->getId());

    return $qb
        ->getQuery()
        ->getResult();
  }
}
